In [1]:
print ('Hello World')

Hello World


In [2]:
message = 'Hello World'
print(message)

Hello World


In [4]:
print ('What is your name?') 

name = input() 

print ('Hello, ', name) 

What is your name?
Migs
Hello,  Migs


In [5]:
name = input('What is your name? ') 

print ('Hello, ', name) 

What is your name? Migs
Hello,  Migs


In [6]:
subjects = ['Math', 'Science', 'English']
print(subjects[0])
print(len(subjects))

Math
3


In [7]:
subjects[1:]

['Science', 'English']

In [0]:
subjects.append('Filipino')

In [0]:
scientist = {'Name:' 'Alan Turing', 'Field:' 'Mathematics'} 

In [0]:
import numpy as np

#create an array
x = np.array([1, 2, 3])

In [0]:
# create a zero array 

a= np.zeros((2,2)) 

 

#create a one array 

b= np.ones((2,2)) 

In [16]:
a/b

array([[0., 0.],
       [0., 0.]])

In [17]:
b/a

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf],
       [inf, inf]])

In [20]:
# create a random int array 

c= np.random.randint (10, size = (5)) 
d= np.random.randint (10, size = (5)) 

print (c, d)
print(c*d)

[8 6 1 7 0] [5 2 1 5 9]
[40 12  1 35  0]


In [22]:
e=np.random.random ((2,2))
print (e)

[[0.94072645 0.16602825]
 [0.89449039 0.0837602 ]]


In [23]:
print(np.sum(c))

22


In [24]:
print(np.sum(e, axis=0))

[1.83521684 0.24978845]


EXERCISE FOR NUMPY

In [37]:
A = np.array([[22, 5, 16, 9], 
     [13, 20, 19, 0], 
     [5, 9, 1, 16], 
     [27, 13, 15, 19]])
B = np.array([[10, 5, 20, 20], 
     [5, 21, 22, 27], 
     [26, 19, 22, 3], 
     [27, 8, 18, 7]])
C = np.array([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
D = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])

print('\n1. Element wise addition: \n', np.add(A,B))
print('\n2. Element wise subtraction: \n', np.subtract(A,B))
print('\n3. Element wise multiplication: \n', np.multiply(A,B))
print('\n4. Matrix Multiplication: \n', np.dot(A,B))
print('\n5. \n', c+d)
print('\n6. \n', c-d)
print('\n7. \n', c*d)
print('\n8. \n', np.dot(c,d))
print('\n9. \n', A+10)
print('\n10. \n', B+10)
print('\n11. \n', c+15)
print('\n12. \n', d+15)
print('\n13. \n', (2*A)+(2*B))
print('\n14. \n', (A+B)*3)
print('\n15. \n', (A-B+A-B+B)*4)



1. Element wise addition: 
 [[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]

2. Element wise subtraction: 
 [[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]

3. Element wise multiplication: 
 [[220  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]

4. Matrix Multiplication: 
 [[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]

5. 
 [13  8  2 12  9]

6. 
 [ 3  4  0  2 -9]

7. 
 [40 12  1 35  0]

8. 
 88

9. 
 [[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]

10. 
 [[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]

11. 
 [23 21 16 22 15]

12. 
 [20 17 16 20 24]

13. 
 [[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]

14. 
 [[ 96  30 108  87]
 [ 54 123 123  81]
 [ 93  84  69  57]
 [162  63  99  78]]

15. 
 [[ 136   20   48   -8]
 [  84   76   64 -108]
 [ -64   -4  -80  116]
 [ 108   72   48  124]]
